### ISSUE TITLE
Preview Email on editor doesn't work 

### ISSUE THREAD

**Issue by maikelthedev** [arikchakma/maily.to#10]
When i go to the live editor and click on preview email I get this

![image](https://github.com/arikchakma/maily.to/assets/29461493/bd554c25-368e-454b-be30-b24de02b65c0)

**Comment by arikchakma** [comment]
Aha, let me have a look.

**Comment by arikchakma** [comment]
@maikelthedev I'm not able to reproduce the issue, can we please try to reload the browser?
<img width="1920" alt="image" src="https://github.com/arikchakma/maily.to/assets/54026804/22a8e45f-7494-4d11-95c3-dffbc87639f7">

**Comment by maikelthedev** [comment]
I'm using Firefox btw.

**Comment by maikelthedev** [comment]
Reloaded browser, keeps being blank

**Comment by maikelthedev** [comment]
I can confirm it works on Edge (Chromium based) but not in Firefox.

**Comment by arikchakma** [comment]
Okay, let me check. Thanks

**Comment by maikelthedev** [comment]
Btw, you're a developer, come to developer-land, we're all waiting for you in Mastodon

**Comment by arikchakma** [comment]
Yes, I'm in. I'm looking into the issue.

**Comment by arikchakma** [comment]
@maikelthedev I'm able to solve it but because of the new `Firefox` guidelines, the font isn't loading.

**Comment by maikelthedev** [comment]
> @maikelthedev I'm able to solve it but because of the new `Firefox` guidelines, the font isn't loading. 

What guidelines? Please elaborate with source links

**Comment by maikelthedev** [comment]
Bravisssimo! 

![image](https://github.com/arikchakma/maily.to/assets/29461493/42a20deb-19b6-4096-8854-12b319b2ee0e)

**Comment by arikchakma** [comment]
Thanks, please create issues if you face any problems, or let me know if you have any feature requests.
