### ISSUE TITLE
Sign Up says fill up email but...where?

### ISSUE THREAD

**Issue by maikelthedev** [arikchakma/maily.to#11]
When I try to Sign Up it says
> enter your email below to create your account...

Then I don't see any field to enter my email

If Github is the only expected way to Sign Up then that sentence is misleading. 
Also if Github is the only way to Sign Up, you're closing the door to every non-techie user (usually most for this kind of thing). 

![image](https://github.com/arikchakma/maily.to/assets/29461493/4ac88d3e-adb0-432d-a24f-1bc3f24dddfb)

**Comment by arikchakma** [comment]
I've removed the text, and I've planned to add a `Google` login also. I'll add it whenever I get some time.

**Comment by maikelthedev** [comment]
You do as you feel able to, there's no rush for FOSS projects. 

But I wouldn't limit it to either forcing people to have Github or Google. 
Specially since your homepage is advertising this as "hassle-free"

**Comment by arikchakma** [comment]
I think you're correct. I'll keep you updated about it.

**Comment by arikchakma** [comment]
I've added `Google` auth for now, and I'll think about the `email` auth later maybe.

Thanks for raising the issue. I'll keep you updated here.
