### ISSUE TITLE
Suggestion: Use MJML instead of custom HTML

### ISSUE THREAD

**Issue by manurana** [arikchakma/maily.to#12]
Project looks great!

Just a suggestion: Creating correct HTML for emails is hard, to take care of various email client eccentricities.
Maybe use something like MJML to do that instead? And let this be just an amazing interface for being creative?

**Comment by arikchakma** [comment]
I have not planned to use it yet but I just wanted to be more flexible from my side. Are you having any problems with this solution?

**Comment by manurana** [comment]
No specific problems @arikchakma !
It might be better for long term maintenance, is all.
Maybe just keep it in the backlog

**Comment by arikchakma** [comment]
Yes, I'll think about it.

Thanks, and let me know if you face any problems.
