### ISSUE TITLE
New editor buttons like image?

### ISSUE THREAD

**Issue by oriole9g** [arikchakma/maily.to#14]
Congratulations on this incredible project!

In the description says you can add logos and it has an image in the email example but, there isn't an image/logo button to add/edit images on editor?

**Comment by arikchakma** [comment]
<img width="859" alt="image" src="https://github.com/arikchakma/maily.to/assets/54026804/6e6ac430-3a66-4fe5-8fe8-586b492034b7">

It's there, please use the slash command (`write / to see command menu`) then type `image` or `logo` you'll find it.
