### ISSUE TITLE
Preview Email button shows empty modal

### ISSUE THREAD

**Issue by iamFoxx** [arikchakma/maily.to#15]
To reproduce:

- open the [playground](https://maily.to/playground) and click on **Preview Email**

**Comment by arikchakma** [comment]
Can you please specify your OS and browser?

**Comment by iamFoxx** [comment]
Hi @arikchakma 

### OS
Windows 10

### Browser
Chrome 
Version 116.0.5845.180 (Official Build) (64-bit)

**Comment by arikchakma** [comment]
<img width="1440" alt="image" src="https://github.com/arikchakma/maily.to/assets/54026804/0a5dc38f-ff95-4712-ba60-9046e6de21cb">

Hello @iamFoxx 

I'm also using Chrome (old version), though on Mac. I'm not able to reproduce it.

**Comment by iamFoxx** [comment]
Sorry. I don't know what's going on with Chrome, but in Firefox, it worked correctly.

#### Chrome 
https://github.com/arikchakma/maily.to/assets/53481612/37328946-acb9-4daa-a7fe-7c5ae2b1f6ec

#### Firefox (114.0.1 (64-bit))
https://github.com/arikchakma/maily.to/assets/53481612/5fb928e8-299f-4594-94bf-e430bbaf209f

**Comment by arikchakma** [comment]
Can you inspect the console and send it to me?

**Comment by iamFoxx** [comment]
![image](https://github.com/arikchakma/maily.to/assets/53481612/eda39a19-4d3e-4db8-b447-0e1d8bd37f6d)

I've recorded with Jam too, check it out: https://jam.dev/c/a6ef2173-46d7-4716-91e9-0f7152f34524

**Comment by arikchakma** [comment]
I can't see any suspicious logs though, I'll check it and let you know.

**Comment by arikchakma** [comment]
@iamFoxx I tried but didn't face anything similar. Can you please try to update Chrome and see?

**Comment by iamFoxx** [comment]
Hi @arikchakma 

I just figured out what happened. The Chrome extension (uBlock Origin) was blocking the modal. 😩
I disabled the extension, and it worked correctly.

**Comment by arikchakma** [comment]
Ahh, thanks for letting me know about it. Let me know if you need any other help.

For now, I'm closing this issue. Thanks @iamFoxx
