### ISSUE TITLE
How tailwindcss is gets converted to inline CSS for  email HTML

### ISSUE THREAD

**Issue by chavda-bhavik** [arikchakma/maily.to#17]
Hey Arik, I'm building an email editor in my project and taking inspiration from maily.to editor.

Can you help me understand, when we click on `Copy Email HTML`, how elements like button styled with tailwindcss gets converted to HTML with inline CSS?

I can find [here](https://github.com/arikchakma/maily.to/blob/3a8dde8cfc4b78bb3c1f39d8f853ed9e213d4958/components/get-html-button.tsx#L21), that Tiptap provides function to convert content to HTML, but how tailwindcss classes gets converted to inline CSS?

Thanks

**Comment by arikchakma** [comment]
Hello Chavda,

Please check [this one](https://github.com/arikchakma/maily.to/blob/main/components/editor/utils/email.ts). You can find everything there.

Thanks
