### ISSUE TITLE
Support for i18n

### ISSUE THREAD

**Issue by BigDog1400** [arikchakma/maily.to#33]
The current version of this library only supports English text. I can think of different application that might need to change the text to different langs (es,en,pt, etc). What do you think about providing the library with translation? 
It could be a prop to the editor instance and then internally get the translations from a JSON file. What are your thoughts on this proposed enhancement?

**Comment by arikchakma** [comment]
Like support for different languages? or for slash command text and everything else?

**Comment by arikchakma** [comment]
I think first we need to add `RTL` support I think, it's really important. What do you think?

**Comment by arikchakma** [comment]
Yeah, we can do that. Let's go for it. I'll think about the `RTL` whenever I get some time.

**Comment by BigDog1400** [comment]
Here is my first proposal to handle the i18n in this package https://github.com/arikchakma/maily.to/pull/34 . I usually use react-intl to handle translations in others projects, but that package relies on context and hooks, and we can't use that in a lot of places in this case. so i went with react-intl-universal which is a fork of react-intl mantained by alibaba and has the flexibility of using translations outside of react. Let me know what you think, right now there is only two langs translated, english and spanish. Also we could add a lang selector in the demo app to see how the editor changes the translations.
