### ISSUE TITLE
Extend variables api configuration

### ISSUE THREAD

**Issue by BigDog1400** [arikchakma/maily.to#35]
Showing a warning for every variable added (that doesn't have a fallback), may cause some confusion for some users. I will like to propose change the api for the variables prop to this
```tsx
type ExtensionsProps = {
  variables?: Array<{
    name: string;
    defaultValue?: string;
    required?: boolean // default to true
  }>
};
```
In this proposal, each variable in the array can have an associated 'name', an optional 'defaultValue', and a 'required' flag that defaults to true. This approach could make the handling of variables more flexible and intuitive for users.

**Comment by arikchakma** [comment]
I agree. Let's not add the `defaultValue` in the props. Only `name` and `required` is fine I think. Because we have to manually add the `fallback value`.
