### ISSUE TITLE
Finding an Alternative to window.prompt

### ISSUE THREAD

**Issue by AustinWildgrube** [arikchakma/maily.to#39]
Hey, 

Love the editor so far! Thanks for all the hard work. I hope to be able to contribute in the future once work settles down for me. I am having an issue, though, and would like to bring it to your attention. Currently, the use of window.prompt is a simple solution, but it might not be the most effective in all situations. For instance, users with pop-ups disabled or those who accidentally activate the "Don't allow this page to display" option might find that nothing happens when they click the image component. This could lead to confusion, as it may seem like the application is not functioning correctly. 

Maybe an alternative approach should be considered, such as using a popover similar to the button component. This could provide a more user-friendly experience, especially for those with certain browser settings that interfere with pop-ups. I'm open to discussion and looking forward to your thoughts on this.

Here's a video of what I mean:

https://github.com/arikchakma/maily.to/assets/40448411/66a39824-88df-4cb8-9456-a99fd0a3f07c

**Comment by arikchakma** [comment]
Ah, good catch. I'll add the popup way directly then.

**Comment by arikchakma** [comment]
@AustinWildgrube we have decided not to implement it now as we've planned to make the editor more customizable where we will solve it easily.
