### ISSUE TITLE
Love this product. Saved me so much time

### ISSUE THREAD

**Issue by CareTiger** [arikchakma/maily.to#4]

**Comment by arikchakma** [comment]
Thanks, let me know if you have any feedback or find any bugs.

**Comment by CareTiger** [comment]
color picker is not working properly. after i try to change the color of text or button there is no "enter" or "save" button

**Comment by arikchakma** [comment]
Make sense, I'll add `buttons` there. Thanks for the feedback.

**Comment by CareTiger** [comment]
you are welcome. great idea and a good product! Also is it possible to integrate tailwind css into the styling?

**Comment by arikchakma** [comment]
I don't have a plan to add tailwind now(for now, maybe later), but I'm planning to add customization for the components.

**Comment by CareTiger** [comment]
is there a plan to save the emails somewhere?  you could connect to a supabase or mongo instance and let users save. this way you can get people to signup. you can enable github auth.

**Comment by arikchakma** [comment]
Yeah, it's already in my pipeline. For sharing the emails also and testing via `resend`.

**Comment by CareTiger** [comment]
how do i upload company logo?

**Comment by arikchakma** [comment]
You can upload somewhere else and paste the URL in the `logo` component.

**Comment by arikchakma** [comment]
@CareTiger I've added the `auth` and `saving templates` features. It's live but I'm fixing the UI.

**Comment by CareTiger** [comment]
let me try

**Comment by arikchakma** [comment]
Sure, let me know about your experience. Tho I'm fixing the UI.
