### ISSUE TITLE
Set the font size of the selected text

### ISSUE THREAD

**Issue by doroved** [arikchakma/maily.to#45]
Please add a font size setting for the selected text, like how it is done for the logo.
<img width="354" alt="image" src="https://github.com/arikchakma/maily.to/assets/30116541/6d80e0e6-74a3-4506-8c50-694dac36f726">

It may be optimal to add a grid from xs to 2xl
<img width="108" alt="image" src="https://github.com/arikchakma/maily.to/assets/30116541/de4247ed-de68-4f86-99be-e8a5946dbbc0">

**Comment by arikchakma** [comment]
It might be a good idea to follow `tailwindcss` typography. I will start working on it after some of my prioritized tasks.

**Comment by arikchakma** [comment]
What do you think if I add a theme config, where you can set the font sizes, line heights, and etc?

**Comment by arikchakma** [comment]
I didn't plan to do it now but in the future or the next version or Maily.
