### ISSUE TITLE
[FeatureRequest] Embed the editor in an existing application

### ISSUE THREAD

**Issue by lucafaggianelli** [arikchakma/maily.to#47]
Hey great idea creating an email editor!

Did you think about embedding it in an existing web app? I have a use case where the user can customise emails sent by my platform and in general I was thinking about email marketing services, etc.

**Comment by arikchakma** [comment]
First of all, sorry for the delay. We don't have a way to embed it right now, you can use the `npm` package to add it to your app if it's using `react`. Or can you explain more about the use case?

**Comment by lucafaggianelli** [comment]
Yeah sorry that was a bit vague.

I have a saas platform from where users can send invoices to clients and reminders in case of missed payments (and also other types of emails) and the users can edit the emails templates. At the moment they can just edit the message, but in the future I wanted to give them more freedom to craft a custom email.

More in general I was thinking about use cases for your editor, if you can use it as a wysiwyg editor for emails in marketing saas and similar.

I'll take a look at the NPM package, it will probably do!

**Comment by arikchakma** [comment]
Yes for this use case you can easily integrate the package, we are using it internally too.

But keep it in mind that the design of the editor is opinionated. If you think it works for you then I would love to help you😊

**Comment by arikchakma** [comment]
@lucafaggianelli I'm closing this issue for now. Let me know if you need anything else.
