### ISSUE TITLE
Standalone editor

### ISSUE THREAD

**Issue by MrRedRhino** [arikchakma/maily.to#51]
Is it possible to use the editor standalone as a component to allow for a custom backend?

**Comment by arikchakma** [comment]
Yes, you can use [@maily-to/core](https://www.npmjs.com/package/@maily-to/core) package in the frontend, and [@maily-to/render](https://www.npmjs.com/package/@maily-to/render) package for rendering HTML in backend.

**Comment by MrRedRhino** [comment]
Aha thank you! Using that with vue is probably quite hard, right?

**Comment by arikchakma** [comment]
Maybe you can write your implementation of the renderer. I have tried that before which was hard to maintain. Now I am using `react-email` for rendering.

**Comment by arikchakma** [comment]
I am closing this issue for now, please don't hesitate to reopen the issue if you have any other questions.
