### ISSUE TITLE
Can't copy email HTML after adding multi line email footer

### ISSUE THREAD

**Issue by ilovefreesw** [arikchakma/maily.to#52]
I am trying to add this in the footer:

```
Copyright © {{right_now.year}}  {{location.name}}, All rights reserved. 
 Want to change how you receive these emails?
 You can [unsubscribe from this list](https://someurl)
```
After adding this, there is an error after I try to copy HTML.

![image](https://github.com/user-attachments/assets/0a243256-ae34-479c-9e78-f9f4377c9f68)

If I remove this footer text then it just works fine....

**Comment by arikchakma** [comment]
I think it's because of copying the text from web pages or text editors. Because on copy it also copies the styles. I would suggest pasting it to Notepad/Apple Notes and then copying it from there.
