### ISSUE TITLE
Customizing editor's styles

### ISSUE THREAD

**Issue by sukhada** [arikchakma/maily.to#53]
Hello! Thank you so much for your work on Maily, I'm finding it super helpful.

I had a question about the best way to implement custom styles in the editor by default (font family, button color, etc). Is the best way to do this to extend the `ThemeOptions` and add the appropriate `fontFamily`/`colors.buttonColor` values? Is there a good way to have these styles rendered in the editor rather than when the email is actually sent with `renderAsync`/`setTheme`?

**Comment by arikchakma** [comment]
Sorry for the late reply, I missed your comment. Currently, it's not possible to customize the editor view, but I am working on the V2 where everything will be customizable.

**Comment by sukhada** [comment]
@arikchakma that's awesome, thank you! Do you have a sense of when V2 will be released?

**Comment by arikchakma** [comment]
I can't promise any time soon, but maybe the end of this year. I will keep everyone updated via email. Let me know if you have any feedback.

**Comment by arikchakma** [comment]
I am closing this issue, feel free to reopen it if you need anything else. Thank you
