### ISSUE TITLE
after adding images unable to edit the email template

### ISSUE THREAD

**Issue by blockiyt** [arikchakma/maily.to#54]
Hey, first of all, great project!

I might have found an issue with inserting "full width" images to the template.
After that, I can't further edit the template, and the image is stuck with a red border around it.
Clicking around does not change anything.

What can I do?

Edit: When there are already some lines with text in it, you can edit the template, if not, you can't, because your stuck in editing the image.

**Comment by arikchakma** [comment]
You can click the `arrow down` key on the keyboard to bypass that, I will add a fix for that in the V2.

**Comment by blockiyt** [comment]
Seems to work fine, thanks!
