### ISSUE TITLE
error when trying to export or render the eMail

### ISSUE THREAD

**Issue by blockiyt** [arikchakma/maily.to#55]
After pressing export to HTML or preview, I get this error message: "An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error."

**Comment by arikchakma** [comment]
It happens whenever you copy the text from an editor or similar editor because they also attach the styles that aren't supported in Maily. So what you can do is copy it to Notepad or Apple Notes, and then paste it from that.
