### ISSUE TITLE
Adding padding and margin in custom pixels in Sections 

### ISSUE THREAD

**Issue by kilgarenone** [arikchakma/maily.to#70]
Hi thanks for making this tool. 

I used to be able to do alot of things in `px` but now seems like they have been replaced by rigid few options 'Smooth', 'Large', 'Smooth' all of which I can't use. 

Are they hidden somewhere? Thanks!

**Comment by arikchakma** [comment]
Hello, we used to allow that but we wanted to make it opinionated instead of having the full control.

If we get more response to add that back we will think about that.

Thank you, please do let me know if you have any other questions.
