### ISSUE TITLE
 Can I embed this in my app?

### ISSUE THREAD

**Issue by Arsenalist** [arikchakma/maily.to#72]
I have an application where users design their own emails. Is it possible to use this project to create an embedded editor in my app?

**Comment by arikchakma** [comment]
If you are using React you can use the package to add the editor into your app. Unfortunately, I don’t have plan to add the embedding right now, maybe later.

**Comment by RUPAAK** [comment]
Hey @arikchakma, is there a way to add text content to the editor without typing. Like for example, I want to add "hello there" by clicking a button, not typing.

**Comment by RUPAAK** [comment]
Hey @arikchakma, is there a way to add text content without typing. Like, I want to add "hello world" by clicking a button without typing anything on the editor
