### ISSUE TITLE
[Feature] Docker image

### ISSUE THREAD

**Issue by ToshY** [arikchakma/maily.to#8]
Hey @arikchakma 👋 

This tool looks really cool and nicely designed 👍  I would love to see a docker image for this editor. Would make it a lot easier to test/play around with it, and eventually self-host it .

Is this something you're interested in adding?

**Comment by arikchakma** [comment]
Currently, I don't have plans to make it a docker image (maybe later). You can `copy & paste` the editor folder into the components and install its `dependencies`. It should work fine.

Thanks, let me know if you need any help.
